let $sidebar = $('.Sidebar')
let $sidebarText = $('.SidebarItemRow')
let $sidebarCollapsible = $('.SidebarRecentsAndFavoritesCollapsible span')
let $sidebarTeamDetailsHeader = $(".SidebarTeamDetailsProjectsList-header")
$sidebar.css('background-color', 'rgba(183,24,24,.55)')
$sidebar.css('text-shadow',  "0px 3px 7px black")
$sidebarCollapsible.css('color', 'white')
$sidebarTeamDetailsHeader.css('color', 'darkgrey')
